### ISSUE TITLE
Identified Tasks and rough roadmap 

### ISSUE THREAD

**Issue by editwentyone** [joinmarket-webui/jam#233]
hey guys, after todays design sync call with @GBKS, we identified the upcoming list of key features and a first draft / rough roadmap, where we as designers can focus and work in design sprints asynch in front of normal development sprints. 

we hope that with this setup we can present exploration results in our 2 weekly community calls in a time boxed manner (~20 min) so we all have something to talk about and iterate on. 

(following list are just our proposal, nothing is set in stone :) ) 

### overall
- postpone translation work until we have final wording and screens/ functionality

### 0.0.6
- secure app with login/logout #120 
- **"visualize mix depths"**: remove privacy shields, implement zoom functionality with neutral level / layer visualization as first alternative (still no jars)
- focus on **"scheduled collaborative tx" aka "tumbler"** as the key feature release #179 

### 0.0.7
- **wallet management**: make one wallet the default, rewire and move already delivered functionality under settings and implement import/export/rescan #228 #137
- implement jm settings inside our **settings area** that the user can manipulate and learn from globally #30 #72
- create an organism **"estimated fee table"** that helps the user to understand upcoming fees 

### 0.0.8
- **coin control** with labels, notes, freeze and unfreeze
- **fidelity bonds** as key feature: to help makers getting picked #31 
- redesign "earn" page with more details and guidance like logs, order book, competitive fee and amount settings

### 0.0.9
- incorporate translation work again
- ?

### … 
- reaching feature parity with jm
- ?

### 1.0?
- rethink the app into even **noob friendlier flows**: no levels, jars, etc - just journeys and flows
- relaunch with visual redesign, design system in the background

please take this list really as a brain dump, note tacking during call and thus a very rough idea what's upcoming, feedback is always welcomed :)

**Comment by dnlggr** [comment]
> we hope that with this setup we can present exploration results in our 2 weekly community calls in a time boxed manner (~20 min) so we all have something to talk about and iterate on.

Nice that sounds great! 🧡 

I like the roadmap! Here and I feel like we'll probably have to make some adjustments but this is definitely the right direction. It's not too far off from our current [milestones](https://github.com/joinmarket-webui/joinmarket-webui/milestones) either. 👌 🛣

_Some off the top of my head feedback:_

For the [upcoming 0.0.6 version](https://github.com/joinmarket-webui/joinmarket-webui/milestone/5), I think realistically "visualize mix depths" won't quite make the cut. Tumbler is likely to be the main focus there so that we can move on quickly to fidelity bonds as the main focus of [in 0.0.7](https://github.com/joinmarket-webui/joinmarket-webui/milestone/6). The reason for doing fidelity bonds before other things is that the Earn screen doesn't really work without fidelity bonds. That's why getting those out quickly is important before we move on to other things.

_I'm thinking something like:_

0.0.6: Main focus: Tumbler
0.0.7: Main focus: Fidelity bonds

After those two things are out, "visualize mix depths" should be the top priority imo -- alongside the other things you listed of course.

☝️ All of that is just my opinion of course. Let me know if it makes sense.

Again, great job I think this is looking good aleady and just needs a few adjustments. Looking forward to hearing @dergigi's opinion as well and to doing some design explorations in the community call. 👌

**Comment by MaxHillebrand** [comment]
This sounds like a stellar roadmap!
