### ISSUE TITLE
Scheduler: implement pause/resume functionality

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#318]
Related to #319

**Comment by dnlggr** [comment]
An upcoming [backend change](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1324/files#diff-bf7adf6effc7b5cce10e099e1f6bd1ec750824dff16d03df9d97aad04d2c811fR163) will likely get rid of the whole concept of pausing/resuming (restarting) a scheduler run. Thus, I'm moving this issue out of the 0.0.10 release. We'll likely be able to close it once we're sure the backend change will make it to master.

**Comment by theborakompanioni** [comment]
This will be closed, since starting with [v0.9.7](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/release-notes/release-notes-0.9.7.md#tumbler-algorithm-fix-and-cycling) "restarting" is deprecated.
Quote:
> Also "restarting" is now the same as starting; it will operate based on whatever mixdepths are funded, there is no "starting mixdepth".

If you think closing this issue is a mistake, please reopen on demand.
