### ISSUE TITLE
Paginate UTXO selection for fidelity bonds

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jam#368]
The UTXO selection list for fidelity bonds can become quite long if there are many UTXOs. We could paginate the list or think of other ways to make it more space efficient.

**Comment by editwentyone** [comment]
because we want to preselect a valid suggestion, and also sort the UTXOs by size and confirmations and CJ status, we could make both lists **scrollable**, so advanced users could maybe scroll through **if needed at all**

any feedback? 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/96262473/212487414-5cd3756c-9de4-4bc7-ad27-1ed550caa5ea.png">

**Comment by theborakompanioni** [comment]
> because we want to preselect a valid suggestion, and also sort the UTXOs by size and confirmations and CJ status, we could make both lists **scrollable**, so advanced users could maybe scroll through **if needed at all**

I think this is already considered in #650, correct?

**Comment by editwentyone** [comment]
yes
