### ISSUE TITLE
Earn: Show counterparty ID to the user

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jam#413]
Raised by @Richie-BTC-Rich in #14:

> After the [earn] service is running a a link to the marketplace with your Counterparty ID would be helpful so you can verify your offer is listed [by looking up your ID in the orderbook]

---

Not sure if the [RPC API](https://joinmarket-org.github.io/joinmarket-clientserver/api/#operation/startmaker) returns the counterparty ID. Doesn't seem like it at a first glance.

**Comment by dnlggr** [comment]
That's a good point. This ID would be the [nick](https://github.com/JoinMarket-Org/JoinMarket-Docs/blob/master/Joinmarket-messaging-protocol.md#pubkey-based-nicks) used for messaging. Not sure how to get to this nick, even on the CLI. Does anyone know?

**Comment by theborakompanioni** [comment]
> That's a good point. This ID would be the [nick](https://github.com/JoinMarket-Org/JoinMarket-Docs/blob/master/Joinmarket-messaging-protocol.md#pubkey-based-nicks) used for messaging if I'm not mistaken. Not sure how to get to this nick, even on the CLI. Does anyone know?

Opened a ticket in the backend repo: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1326

**Comment by theborakompanioni** [comment]
e.g. as far as I can see, joininbox currently parses the nickname from the log files: https://github.com/openoms/joininbox/blob/6c177a71d8fcb87c93d6b3061ffee2393b926b3d/scripts/_functions.sh#L163

In order to do it the same way, a server side script running alongside `jmwalletd` that serve this data via an api would be needed.
Let's wait for a response in https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1326 and then decide what to do.

Having an own `jamd` running that adds some missing features would definitely be beneficial (however, it also introduces a lot of drawbacks..)..

**Comment by dnlggr** [comment]
I'm moving this out of v0.0.10. I don't think this will become unblocked in the coming days.
