### ISSUE TITLE
No connection to backend: The server reported a problem: 502 Bad Gateway.

### ISSUE THREAD

**Issue by scissorstail** [joinmarket-webui/jam#502]
Hello.
I installed this app from umbrel appstore. but It is just not working...
I tried reinstall this app and reboot umbrel server several times, but it is no use.

Anyway... I am a average web dev. I can access docker containers and file system.
If you want some logs or something help, I can. 

---
### My environments
hw: Raspberry Pi 4
os: [umbrel](https://github.com/getumbrel/umbrel)

---
## Screenshot
![image](https://user-images.githubusercontent.com/93466598/190837447-694e696d-1ffa-4deb-b04a-498f62098bba.png)

**Comment by theborakompanioni** [comment]
>  I installed this app from umbrel appstore. but It is just not working... I tried reinstall this app and reboot umbrel server several times, but it is no use.

Hey @scissorstail, thanks for the report!
This is a known problem with v0.0.10 in combination with Bitcoin Core v23 - the setup script did not take into account the change of descriptor wallets to be the default.. JM needs non-descriptor wallets.. it is already fixed in the current v0.1.0 release. I am very sorry that this happened.

You can find [the PR updating the umbrel app here](https://github.com/getumbrel/umbrel-apps/pull/153). This should resolve the issue you are experiencing. You might need to manually delete the descriptor wallet that has been created.
Would you possibly be so kind as to report if that did not fix the problem for you?

Other than that: Any help is highly appreciated. v0.1.0 was the first milestone which should already contain the most important features. But there are upcoming features which would be nice to have in the near future. Also, the code base is a bit rough and refactoring and/or some cleaning up would be great!

**Comment by theborakompanioni** [comment]
@scissorstail With the PR merged, this should now be resolved. Would you be able to report if it fixes the problem for you?

You will have to remove the wallet file/directory before!
I guess there is very little information on how to do this, as normally, you should not have to delete wallets in the first place. I don't know if it is necessary, but I'd 
1. uninstall Jam, 
2. unload the wallet via `unloadwallet`, 
3. delete/rename the Bitcoin Core wallet file/directory (on Umbrel it is named `jam_default`), and 
4. restart your node. 
5. Install Jam again

**Please make sure you have all backups in place**. Better safe than sorry.
As I understand, it has never worked for you, so you need to create a new wallet afterwards.
Otherwise and existing wallet can be [imported via command line](https://jamdocs.org/FAQ/#can-i-import-an-existing-wallet).

**Comment by scissorstail** [comment]
It is not working. 
because there is no [code for replace already created wallet](https://github.com/joinmarket-webui/jam-docker/blob/4f6e1c3eba983800718e9e7398f540f73faee281/standalone/jam-entrypoint.sh#L72-L101)

I just about to search that 'how to remove wallet?'😂😂😂

Maybe `bitcoin-cli unloadwallet jam_default` fix this. I am going to do this after backup.

Thanks.

**Comment by theborakompanioni** [comment]
> It is not working. because there is no [code for replace already created wallet](https://github.com/joinmarket-webui/jam-docker/blob/4f6e1c3eba983800718e9e7398f540f73faee281/standalone/ja
> 
> Maybe `bitcoin-cli unloadwallet jam_default` fix this. I am going to do this after backup.

Yeah, you definitely need to remove the specific `jam_default` wallet directory of Bitcoin Core after `unloadwallet`.

> Thanks.

Would be nice to know. It'd be good to be able to link to this issue for all others having the same problem.

**Comment by scissorstail** [comment]
I think `bitcoin-cli unloadwallet jam_default false` is more safe. 
https://developer.bitcoin.org/reference/rpc/unloadwallet.html

![1](https://user-images.githubusercontent.com/93466598/191267534-e93f0c9f-762f-4601-a1e9-5f46b0a2664b.png)


It is working. but It is too dangereous to do this...

So what is this app do?🤣

Thanks.
