### ISSUE TITLE
"gzip" directive is duplicate in joinmarket_webui_ssl.conf:16

### ISSUE THREAD

**Issue by Lobbelt** [joinmarket-webui/jam#557]
Installed JAM on my Raspiblitz (running on Raspberry Pi 4) today. 

After install, I tried to look at the status of Electrs, but it said nginx had failed. When I run `sudo nginx -t`, I get the following:

`nginx: [emerg] "gzip" directive is duplicate in /etc/nginx/sites-enabled/joinmarket_webui_ssl.conf:16`
`nginx: configuration file /etc/nginx/nginx.conf test failed`

Can I somehow fix this?

**Comment by theborakompanioni** [comment]
Hey! Thanks for the heads-up!
This should be fixed with https://github.com/rootzoll/raspiblitz/pull/3321
and will be released with RaspiBlitz v1.8.

A possible workaround is probably to remove the line `include /etc/nginx/snippets/gzip-params.conf;` from `joinmarket_webui_ssl.conf`: https://github.com/rootzoll/raspiblitz/blob/v1.8/home.admin/assets/nginx/sites-available/joinmarket_webui_ssl.conf#L11

But I am not sure if this version is even working as expected on RaspiBlitz.. you might want to wait for RaspiBlitz v1.8.1..

**Comment by theborakompanioni** [comment]
Hey @Lobbelt, did you manage to make it work?

**Comment by Lobbelt** [comment]
Sorry I didn't end up using the workaround, I just flashed a fresh install of Raspiblitz on the SD card and took it from there. Holding off on JAM for now. :-)

**Comment by theborakompanioni** [comment]
> Sorry I didn't end up using the workaround, I just flashed a fresh install of Raspiblitz on the SD card and took it from there. Holding off on JAM for now. :-)

k. Thanks for the quick response. Closing the issue now, if that is okay. Feel free to reopen if you think this is a mistake or report back in case you try it again :orange_heart:
