### ISSUE TITLE
DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated.

### ISSUE THREAD

**Issue by 4ezb2** [joinmarket-webui/jam#768]
Jam was installed using the guides from [Raspibolt](https://raspibolt.org/guide/bonus/bitcoin/Jam.html) and still functions as expected since several months. However, there is a warning in the logs after starting jam after it was updated to  v0.2.0

## Steps to reproduce
  1. sudo systemctl start jam.service
  2. sudo journalctl -fu jam
  3. See Warning in logs, as shown below.

## System specifications
  - Version: v0.2.0 - Renewing Rhubarb
  - Operating system = ubuntu server
  - Browser: Firefox

```
ubuntu npm[75441]: [HPM] Proxy created: /obwatch/  -> http://127.0.0.1:62601
ubuntu npm[75441]: [HPM] Proxy rewrite rule created: "^/obwatch/" ~> ""
ubuntu npm[75441]: (node:75441) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
ubuntu npm[75441]: Starting the development server...
ubuntu npm[75441]: Compiled successfully!
ubuntu npm[75441]: You can now view jam in the browser.
```

**Comment by theborakompanioni** [comment]
Hey @4ezb2! Thanks for the report!

I am not familiar with RaspiBolt, but I tried to address this in #769 and is hopefully resolved.
It seems their setup already includes an nginx, so it would have been nice to just deliver Jams static build instead of running `npm start` - however, as I am not into it, there might be reasons for them to do so.

Thanks again :pray: 
If you have any other feedback or comments, please feel free to create another issue! :orange_heart:

**Comment by 4ezb2** [comment]
hi @theborakompanioni thanks for the super quick response. Feel free to close this issue as I am optimistic that your fix will work. 🧡

**Comment by theborakompanioni** [comment]
> hi @theborakompanioni thanks for the super quick response. Feel free to close this issue as I am optimistic that your fix will work. 🧡

Hey, let's do the normal procedure with reviews, tests, approval and stuff :wink: 
Thanks for your report, brother :pray:
